# Generated by Django 3.1.7 on 2022-03-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='pin_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
