# Generated by Django 3.1.7 on 2022-03-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Transaction',
        ),
    ]
