# Generated by Django 3.1.7 on 2022-04-01 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
