# Generated by Django 3.1.7 on 2022-04-08 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0002_auto_20220408_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
