# Generated by Django 3.1.7 on 2022-04-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0003_auto_20220401_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
