# Generated by Django 3.1.7 on 2022-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0003_auto_20220408_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='not_bottle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
