# Generated by Django 3.1.7 on 2022-04-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0004_auto_20220408_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
