# Generated by Django 3.1.7 on 2022-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvm', '0004_deposit_not_bottle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='not_bottle',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
